# NumPy Exercises 


## Defining an array


#### Import NumPy as np

In [114]:
import numpy as np

#### Create an array of 10 zeros 

In [115]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [116]:
x = np.ones(10)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 tens

In [117]:
x = np.full(10,10)
x

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

#### Create an array of the integers from 10 to 100

In [118]:
x = np.arange(10,101,1)
x

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

#### Create an array of all the odd integers from 10 to 30

In [119]:
x = np.arange(11,31,2)
x

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

#### Create a 3x3 array with values ranging from 0 to 8 

In [120]:
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
My_2DArray = a
My_2DArray

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create an array of 25 random numbers between 0 and 1

In [121]:
x = np.random.rand(25)
x


array([0.04430022, 0.09353511, 0.03711584, 0.56833584, 0.7954843 ,
       0.82333016, 0.16013311, 0.11714636, 0.46190383, 0.64061889,
       0.93983294, 0.92849416, 0.00925765, 0.62570374, 0.04245471,
       0.25657584, 0.01445637, 0.01209485, 0.83059542, 0.35796007,
       0.71386366, 0.97379588, 0.02476106, 0.46656979, 0.74840983])

#### Create an array of 40 linearly spaced points between 0 and 10:

In [122]:
x = np.linspace(0,10,40)
x

array([ 0.        ,  0.25641026,  0.51282051,  0.76923077,  1.02564103,
        1.28205128,  1.53846154,  1.79487179,  2.05128205,  2.30769231,
        2.56410256,  2.82051282,  3.07692308,  3.33333333,  3.58974359,
        3.84615385,  4.1025641 ,  4.35897436,  4.61538462,  4.87179487,
        5.12820513,  5.38461538,  5.64102564,  5.8974359 ,  6.15384615,
        6.41025641,  6.66666667,  6.92307692,  7.17948718,  7.43589744,
        7.69230769,  7.94871795,  8.20512821,  8.46153846,  8.71794872,
        8.97435897,  9.23076923,  9.48717949,  9.74358974, 10.        ])

## Indexing 


In [123]:
#You are given the following 2D array
a = np.arange(1,25).reshape(4,-1)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [124]:
# Use array indexing to select the subset that contains 9,10,11,12,15,16,17,18,21,22,23,24. 
# In other words, the 3 * 4 sub-matrix in the bottom right corner of your array
# I have shown you the output -- be careful, if you run your code, it is going to "wipe out" my output
a[1:,2:]

array([[ 9, 10, 11, 12],
       [15, 16, 17, 18],
       [21, 22, 23, 24]])

In [125]:
# Use array indexing  get the value 20, as my output shows
a[3,1]

20

In [126]:
# Use array indexing  get the column 10, 16, 22, as my output shows
a[1:,3, None]

array([[10],
       [16],
       [22]])

In [127]:
# Use array indexing  get the row [15,16,17] as my output shows
a[2,2:5]

array([15, 16, 17])

### Now the hard task!

#### Write a function that gives the users four random integers between 1 and 10 and ask them to enter the square number of them. If the user answers all of them correctly, congratulate them. Otherwise, show them the right answer

In [128]:
# Step 0: Import numpy -- ALWAYS import all the libraries you need at the beginning!
import numpy as np
import random

#Step 1: Function creation -- refer to the last lab for the syntax of function creation
# does our function take parameters?
# Create your function here:

def getrandomsq():
    
#Step 2: Create an array of four random integers between 1 and 10 

    rand_numbers = np.asarray(random.sample(range(1,11),4))
    squares = [number*number for number in rand_numbers]

#Step 3: Print your numbers

    print("Enter Square of Number", rand_numbers)

#Step 4: Prompt the user to enter four numbers, ONE AT A TIME. Use a loop to store these four numbers in a new array
#  HINT 1: We could take all four numbers in through one line, but to practice loop, let's do it the hard way
#  HINT 2: You can start by creating an empty array -- np.array([]), then appending to it one at a time
#  HINT 3: Remember, input() only returns STRINGS. You need to turn them into integers


    input_array = np.array([],dtype=int)
    for i in range (0,4):
        print("Enter square of " + str(rand_numbers[i]) + ": ",end="")
        num = int(input(""))
        input_array = np.append(input_array,num)

#Step 5: Now that you have the two arrays, you can compare them using array functions and decide whether the answers are correct
#  HINT 4: To compare two arrays, you can use array1 == array2 -- however, you have to use a variable to hold the result
#          The resulted array is an array of Boolean values. To quickly check whether it contains true value, you might want to
#          use the all() or any() function...

    result = input_array == squares
    if all(result) == True:
        print("Congratulations...")
    else:
        print('Wrong Answers:')
        for i in range(0,len(result)):
            if result[i] == False:
                print("You entered square of {} as {}. The correct square value is {}".format(rand_numbers[i],input_array[i],squares[i]))
getrandomsq()

Enter Square of Number [1 6 7 4]
Enter square of 1: 

ValueError: invalid literal for int() with base 10: ''