# NumPy Exercises 


## Defining an array


#### Import NumPy as np

#### Create an array of 10 zeros 

#### Create an array of 10 ones

#### Create an array of 10 tens

#### Create an array of the integers from 10 to 100

#### Create an array of all the odd integers from 10 to 30

#### Create a 3x3 array with values ranging from 0 to 8 

#### Create an array of 25 random numbers between 0 and 1

#### Create an array of 40 linearly spaced points between 0 and 10:

## Indexing 


In [5]:
#You are given the following 2D array
a = np.arange(1,25).reshape(4,-1)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [6]:
# Use array indexing to select the subset that contains 9,10,11,12,15,16,17,18,21,22,23,24. 
# In other words, the 3 * 4 sub-matrix in the bottom right corner of your array
# I have shown you the output -- be careful, if you run your code, it is going to "wipe out" my output


array([[ 9, 10, 11, 12],
       [15, 16, 17, 18],
       [21, 22, 23, 24]])

In [10]:
# Use array indexing  get the value 20, as my output shows


20

In [8]:
# Use array indexing  get the column 10, 16, 22, as my output shows


array([[10],
       [16],
       [22]])

In [9]:
# Use array indexing  get the row [15,16,17] as my output shows


array([[15, 16, 17]])

### Now the hard task!

#### Write a function that gives the users four random integers between 1 and 10 and ask them to enter the square number of them. If the user answers all of them correctly, congratulate them. Otherwise, show them the right answer

In [ ]:
# Step 0: Import numpy -- ALWAYS import all the libraries you need at the beginning!
import numpy as np

#Step 1: Function creation -- refer to the last lab for the syntax of function creation
# does our function take parameters?
# Create your function here:

    
#Step 2: Create an array of four random integers between 1 and 10 
   
#Step 3: Print your numbers


#Step 4: Prompt the user to enter four numbers, ONE AT A TIME. Use a loop to store these four numbers in a new array
#  HINT 1: We could take all four numbers in through one line, but to practice loop, let's do it the hard way
#  HINT 2: You can start by creating an empty array -- np.array([]), then appending to it one at a time
#  HINT 3: Remember, input() only returns STRINGS. You need to turn them into integers














#Step 5: Now that you have the two arrays, you can compare them using array functions and decide whether the answers are correct
#  HINT 4: To compare two arrays, you can use array1 == array2 -- however, you have to use a variable to hold the result
#          The resulted array is an array of Boolean values. To quickly check whether it contains true value, you might want to
#          use the all() or any() function...





    