# In this session, we learn NumPy Array, the building block of many other more advanced data structures

## <font color="red"> NumPy Array </font>

## <font color="blue"> 1. Define An Array </font>

In [2]:
# An NumPy array can be created from a Python list

# Notice that we need to import a package to use it. It is recommended that you name it something short like np, but 
# you are not required to

import numpy as np
p_list = [1,2,3]
print(p_list)
a1 = np.array(p_list)
print(a1)

[1, 2, 3]
[1 2 3]


In [3]:
# To build an array from scratch, you could use the "arange" function -- it is very similar to Python's own range function

# In Python:
x = list(range(10))

# In NumPy:
y = np.arange(10)

print(x,y)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] [0 1 2 3 4 5 6 7 8 9]


In [5]:
# you can make full use of the arange() function's parameters, just as you would for range()
y = np.arange(2,20,2)
# use the "Tab + Shift" trick when your mouse is at the end of the arange word, see what these three paramters are
# guess what the output looks like?
print(y)

[ 2  4  6  8 10 12 14 16 18]


In [9]:
# Exercise 1: Create an array that includes all even numbers between 20 and 50 inclusive
x = np.arange(20,52,2)
print(x)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [10]:
# The cool thing about array is that you have many helpful functions when defining one
# Try zeros() function:
x = np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [11]:
# It makes an array of zeros! you can also use the ones() function:
x = np.ones(5)
print(x)
# Crazy, isn't it? Is there a twos() function? You can try it out

[1. 1. 1. 1. 1.]


In [13]:
# There is no "twos()" function. However, there is the full() function....
# Exercise 2: Use the Tab+Shift trick to learn how the full() function works. Create an array of 10 5's

x = np.full(10,5)
print(x)

[5 5 5 5 5 5 5 5 5 5]


In [14]:
# My favorite is the linspace() function -- you hear it right, it is named under me! :)
x = np.linspace(0,8,20)
print(x)
# Can you guess what it does?

[0.         0.42105263 0.84210526 1.26315789 1.68421053 2.10526316
 2.52631579 2.94736842 3.36842105 3.78947368 4.21052632 4.63157895
 5.05263158 5.47368421 5.89473684 6.31578947 6.73684211 7.15789474
 7.57894737 8.        ]


In [16]:
# Exercise 3: Create an array of 500 numbers that are evenly distributed between 1 and 100 inclusive
x = np.linspace(1,100,500)
print(x)

[  1.           1.19839679   1.39679359   1.59519038   1.79358717
   1.99198397   2.19038076   2.38877756   2.58717435   2.78557114
   2.98396794   3.18236473   3.38076152   3.57915832   3.77755511
   3.9759519    4.1743487    4.37274549   4.57114228   4.76953908
   4.96793587   5.16633267   5.36472946   5.56312625   5.76152305
   5.95991984   6.15831663   6.35671343   6.55511022   6.75350701
   6.95190381   7.1503006    7.34869739   7.54709419   7.74549098
   7.94388778   8.14228457   8.34068136   8.53907816   8.73747495
   8.93587174   9.13426854   9.33266533   9.53106212   9.72945892
   9.92785571  10.12625251  10.3246493   10.52304609  10.72144289
  10.91983968  11.11823647  11.31663327  11.51503006  11.71342685
  11.91182365  12.11022044  12.30861723  12.50701403  12.70541082
  12.90380762  13.10220441  13.3006012   13.498998    13.69739479
  13.89579158  14.09418838  14.29258517  14.49098196  14.68937876
  14.88777555  15.08617234  15.28456914  15.48296593  15.68136273
  15.87975

In [17]:
# Creating a random array:
x = np.random.rand(10)
print(x)

[0.81134716 0.96879004 0.90752801 0.60350679 0.42830742 0.19353511
 0.33091775 0.11314825 0.33232951 0.84484882]


In [18]:
# The "rand" function ONLY generates numbers between zero and one
# To make bigger integers, you can use randint
x = np.random.randint(20,40,5)
x

array([34, 21, 35, 35, 20])

In [19]:
# Exercise 4: Create a list of 100 random integers between 20 and 50
x = np.random.randint(20,50,100)
x

array([38, 24, 47, 35, 34, 21, 26, 43, 30, 20, 29, 47, 21, 39, 36, 41, 31,
       48, 45, 41, 31, 47, 47, 37, 32, 44, 38, 30, 47, 44, 21, 35, 48, 23,
       42, 36, 48, 26, 26, 27, 23, 24, 45, 44, 45, 25, 45, 23, 28, 47, 41,
       34, 40, 48, 44, 33, 22, 29, 39, 41, 29, 44, 26, 49, 38, 40, 40, 25,
       41, 49, 20, 42, 31, 39, 42, 24, 22, 38, 39, 29, 35, 23, 25, 49, 46,
       26, 27, 49, 20, 35, 46, 31, 48, 21, 21, 30, 41, 41, 27, 31])

## <font color="blue"> 2. Reading Operations in Array </font>

In [20]:
# If you have no trouble with list indexing, this section should be a piece of cake for you, too
# To access one element of an array, it is exactly the same as how you would do it in Python list:
a = np.arange(1,11)
print(a)
print(a[4])
print(a[6])
# Remember that all Python indexes start at 0

[ 1  2  3  4  5  6  7  8  9 10]
5
7


In [21]:
# To access more than one element, use the operator ":" to take a "slice"
print(a[4:6])

[5 6]


In [23]:
# Exercise 5: Question -- does slicing (using index to take a portion of an array) return a new array, or merely a reference to
# part of the old array? Write code to find out
a = np.arange(1,11)
b = print(a[4:6])
print(id(a))
print(id(b))

[5 6]
4723576048
4484492736


In [24]:
# You can leave out the index. Leaving out the left means it starts at 0. Leaving out the right means all the way to the end
print(a[:5])
print(a[6:])
print(a[:])

[1 2 3 4 5]
[ 7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [25]:
# Negative Indexes: Why don't you run the following and decide how negative indexes work?
print(a[-1])
print(a[-4])
print(a[:-1])
print(a[-1:])

10
7
[1 2 3 4 5 6 7 8 9]
[10]


## <font color="blue"> 3. Writing Operations in Array </font>

In [26]:
np.append(a,[11,12])
a
#What happened? Why is a not changed?

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
b = np.append(a,[10,11])
print(id(a))
print(id(b))
print(a,b)

4723576048
4724283696
[ 1  2  3  4  5  6  7  8  9 10] [ 1  2  3  4  5  6  7  8  9 10 10 11]


In [28]:
#Notice how the append function in array differs from the append function in list
test1 = [1,2,3]
test2 = test1.append(4)
print(test1,test2)
print(id(test1),id(test2))

[1, 2, 3, 4] None
4725054144 4484492736


In [ ]:
# In List, the append() function does NOT return any value. It just adds an element to the original list
# In Array, the append() function actually creates a NEW array using the parameter being given

In [29]:
# ADVENCED: Array and list is the SAME when it comes to being mutable objects.
a = np.array([1,2,3])
b = a
b[2] = 34
print(a)
#What do you think will be the result?

[ 1  2 34]


In [30]:
# What do we do if we want a COPY of an array, not just a reference to it? This way, we can change it all we want
# without worrying about messing up the original
a = np.array([1,2,3])
b = a.copy()
print(id(a))
print(id(b))
b[1] = 20
print(a,b)

4720157104
4720157872
[1 2 3] [ 1 20  3]


## <font color="blue"> 4. 2D Array and List </font>

In [31]:
# We can also define a 2D list:
my_2DList = [[1,2],[3,4],[5,6]]
my_2DList

[[1, 2], [3, 4], [5, 6]]

In [32]:
# And a 2D array:
my_2DArray = np.array(my_2DList)
my_2DArray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
# With 2D array, indexing is even more confusing
a3 = np.array([[1,2,3,4,5],[6,7,8,9,10], [11,12,13,14,15]])
a3
# Exercise 6: Given the array above, let's see if you could correctly predict the outcome of the following codes:
print(a3[2,3])
print(a3[:2,3:])
print(a3[1:3,1:2])
print(a3[:-1,-2:])

14
[[ 4  5]
 [ 9 10]]
[[ 7]
 [12]]
[[ 4  5]
 [ 9 10]]


In [ ]:
#We use the shape ATTRIBUTE to show the shape of a 2D array:
my_2DArray.shape

In [34]:
# We can use the reshape() method to reshape our array:
my_2DArray.reshape(1,6)
print(my_2DArray)
my_2DArray.reshape(6,1)
print(my_2DArray)
my_2DArray.reshape(2,3)
print(my_2DArray)
# Why don't they change? What happened?

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# Exercise 7: Fix the errors above:


In [35]:
# A very useful way to use the reshape() function is to use "-1" to let the function decide the number of rows to create
testArray = np.random.randint(2,100,(4,6))
print(testArray)
x= testArray.reshape(3,-1)
print(x)
y=testArray.reshape(12,-1)
print(y)
z=testArray.reshape(8,-1)
print(z)
w=testArray.reshape(2,-1)
print(w)

[[86 76 57 25 92 97]
 [37  2 95  8 94 25]
 [96 93 52  3 22 56]
 [24 76 45 55 53 36]]
[[86 76 57 25 92 97 37  2]
 [95  8 94 25 96 93 52  3]
 [22 56 24 76 45 55 53 36]]
[[86 76]
 [57 25]
 [92 97]
 [37  2]
 [95  8]
 [94 25]
 [96 93]
 [52  3]
 [22 56]
 [24 76]
 [45 55]
 [53 36]]
[[86 76 57]
 [25 92 97]
 [37  2 95]
 [ 8 94 25]
 [96 93 52]
 [ 3 22 56]
 [24 76 45]
 [55 53 36]]
[[86 76 57 25 92 97 37  2 95  8 94 25]
 [96 93 52  3 22 56 24 76 45 55 53 36]]


## <font color="blue"> 5. Helpful Functions and Methods </font>

In [36]:
# Min and Max always come in handy:
a = np.arange(1,11)
print(a.min())
print(a.max())

1
10


In [37]:
# We can also find WHERE the min and max are in an array -- this will come in handy later
import random
a = np.arange(1,11)
random.shuffle(a)
print(a)
print(a.argmin())
print(a.argmax())

[ 2  1  8  6 10  3  4  5  9  7]
1
4


In [38]:
# IMPORTANT! One MAJOR advantage of NumPy Array over List is that we could do ARITHMETICS with them
# Natural, considering that NumPy was developed for LINEAR ALGEBRA
# First let us look at "+"
l1 = [1,2,3]
l2 = [4,5,6]
#Guess what will happen if we do l1 + l2?

In [39]:
#Exercise 5: Apply "+" to the two lists above and see what you get
l1+l2

[1, 2, 3, 4, 5, 6]

In [40]:
#Exercise 6: Apply "+" to the two arrays below and see what happens:
a1 = np.array(l1)
a2 = np.array(l2)
a1 + a2

array([5, 7, 9])

In [41]:
#Array allows you to apply "+" to CORRESPONDING ELEMENTS, very convenient for vector arithmetics
a1 - a2

array([-3, -3, -3])

In [42]:
a1 * a2

array([ 4, 10, 18])

In [43]:
a1 / a2
#Warning: be careful about a2 containing zeros!

array([0.25, 0.4 , 0.5 ])

In [44]:
a1 ** 2

array([1, 4, 9])

In [45]:
#Some useful numPy array math functions:
np.sqrt(a1)

array([1.        , 1.41421356, 1.73205081])

In [46]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [47]:
#sum functions
# It is often needed to calculate the sum of elements of an array -- it is very easy
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a.sum())
print(a.cumsum())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[ 1  3  6 10 15 21 28 36 45]


In [48]:
#VERY IMPORTANT! Boolean Indexing
# A very useful way to index array is to use Boolean indexing. Guess what the following code returns:
y = np.arange(10)
print(y)
print(y>4)

[0 1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True  True]


In [49]:
# When you use comparison on an array, it returns A LIST OF BOOLEAN VALUES
# We can then use this list as index to feed back into the array. This is called Boolean Indexing
print(y/3>2)
print(y[y/3>2])

[False False False False False False False  True  True  True]
[7 8 9]
